### ISSUE TITLE
Nemp is overlapping the taskbar

### ISSUE THREAD

**Issue by Trolldemorted** [DanielGausi/Nemp#1]
As I had previously reported in the [forum](https://www.entwickler-ecke.de/viewtopic.php?p=705399#705399): If you maximize nemp on W10, it will overlap the taskbar. The "disable extended skin system" workaround works, but nevertheless

- users on the affected platforms should not be required do disable the workaround manually, it should be default
- you might want to investigate which other windows versions are affected (e.g. W8 and W8.1)
- eventually the bug should be fixed

Since W10 is the only platform with a growing userbase it would be sad if nemp would not work properly on it. If you need testers, just say the word.

**Comment by DanielGausi** [comment]
Is this still an issue with the most recent version 4.9.0? I can reproduce this behaviour in 4.8, but with the current version it should be working as intended.

**Comment by Trolldemorted** [comment]
I have just updated to 4.9.0 and you are indeed correct, the fullscreen does no longer overlap the taskbar. Unfortunately the drawing performance is not great (>1 seconds redraw time after maximizing the window), and if you resize the window with a mouse nemp occupies an entire cpu core while you are dragging. Was that always the case with extended skin system enabled?

**Comment by DanielGausi** [comment]
@ CPU while dragging: This happens to almost every program on my system (Win10 x64), including Thunderbird, MS Word, Windows Explorer, Firefox, Internet Explorer, ... this is not a Nemp issue, I would say.

@ redraw time: I can't see such a bad performance when maximizing/normalizing the window. 

Switching the skin however does take some time. This is a general issue with the VCL Themes, as switching between themed/non-themed window requires a re-creation of all the controls. (but to be honest: There are some "Altlasten" in the code regarding the skin system ... there may be a few "repaints" too much when switching the skin, but it was necessary back then)

**Comment by Trolldemorted** [comment]
You are right about dragging! Fascinating that a few redraws consume so much cpu time. Nevertheless, nemp behaves quite sluggish while drag-resizing on my machine.

Yeah I think the "going fullscreen delay" is caused by many redraw calls - I can observe how individual parts of the window are being repainted, and they are doing it multiple times with different paddings. E.g. the "Nemp - noch ein mp3 player" title bar text is painted once without padding (the N is exactly at the top end of my screen), and after a few miliseconds it gets repainted with padding (it hops a few pixels south-east).

Nevertheless this issue is solved, thanks a lot!
